import type { ThemeDefinition } from '../../shared/domain/theme-colors';

export const DEFAULT_LIGHT_THEME: ThemeDefinition = {
  name: 'Light',
  colors: {
    'color-bg': '#f7f7f8',
    'color-bg-subtle': '#f0f0f2',
    'color-surface': '#ffffff',
    'color-surface-hover': '#f8f8fa',
    'color-border': '#e1e1e6',
    'color-border-strong': '#c9c9d1',
    'color-text': '#1d1c1d',
    'color-text-muted': '#69676b',
    'color-text-subtle': '#99979c',
    'color-text-inverse': '#ffffff',
    'color-accent': '#611f69',
    'color-accent-hover': '#4a154b',
    'color-accent-subtle': '#f3e8f5',
    'color-accent-text': '#ffffff',
    'color-danger': '#e01e5a',
    'color-danger-hover': '#c4174e',
    'color-danger-subtle': '#fce8ef',
    'color-success': '#2eb67d',
    'color-success-subtle': '#e5f7f0',
    'color-warning': '#ecb22e',
    'color-warning-subtle': '#fff7df',
    'color-info': '#36c5f0',
    'color-info-subtle': '#e5f8fd',
    'color-focus-ring': 'rgba(97, 31, 105, 0.35)',
  },
};

export const DEFAULT_DARK_THEME: ThemeDefinition = {
  name: 'Dark',
  colors: {
    'color-bg': '#121214',
    'color-bg-subtle': '#18181b',
    'color-surface': '#1e1e22',
    'color-surface-hover': '#26262c',
    'color-border': '#2e2e36',
    'color-border-strong': '#3d3d48',
    'color-text': '#ececee',
    'color-text-muted': '#a8a8b0',
    'color-text-subtle': '#787880',
    'color-text-inverse': '#ffffff',
    'color-accent': '#9b59b6',
    'color-accent-hover': '#8e44ad',
    'color-accent-subtle': '#2a1f33',
    'color-accent-text': '#ffffff',
    'color-danger': '#e01e5a',
    'color-danger-hover': '#ff4d7a',
    'color-danger-subtle': '#3d1a28',
    'color-success': '#2eb67d',
    'color-success-subtle': '#1a3d2e',
    'color-warning': '#ecb22e',
    'color-warning-subtle': '#3d3520',
    'color-info': '#36c5f0',
    'color-info-subtle': '#1a3540',
    'color-focus-ring': 'rgba(155, 89, 182, 0.4)',
  },
};

export const DEFAULT_SPACE_THEME: ThemeDefinition = {
  name: 'Space',
  colors: {
    'color-bg': '#070b14',
    'color-bg-subtle': '#0c1220',
    'color-surface': '#121a2e',
    'color-surface-hover': '#182038',
    'color-border': '#1e2a42',
    'color-border-strong': '#2a3a5c',
    'color-text': '#e4eaf7',
    'color-text-muted': '#8b9dc3',
    'color-text-subtle': '#5c6f8f',
    'color-text-inverse': '#ffffff',
    'color-accent': '#6b8afd',
    'color-accent-hover': '#5580f0',
    'color-accent-subtle': '#151f3a',
    'color-accent-text': '#ffffff',
    'color-danger': '#f87171',
    'color-danger-hover': '#ef4444',
    'color-danger-subtle': '#2a1515',
    'color-success': '#4ade80',
    'color-success-subtle': '#152a1e',
    'color-warning': '#fbbf24',
    'color-warning-subtle': '#2a2215',
    'color-info': '#38bdf8',
    'color-info-subtle': '#152530',
    'color-focus-ring': 'rgba(107, 138, 253, 0.4)',
  },
};

export const DEFAULT_HACKCLUB_THEME: ThemeDefinition = {
  name: 'Hack Club',
  colors: {
    'color-bg': '#0f1219',
    'color-bg-subtle': '#151a24',
    'color-surface': '#1c2230',
    'color-surface-hover': '#242b3c',
    'color-border': '#2a3344',
    'color-border-strong': '#3d4659',
    'color-text': '#f5f7fa',
    'color-text-muted': '#8492a6',
    'color-text-subtle': '#6b7789',
    'color-text-inverse': '#ffffff',
    'color-accent': '#ec3750',
    'color-accent-hover': '#d42f47',
    'color-accent-subtle': '#2a1519',
    'color-accent-text': '#ffffff',
    'color-danger': '#ec3750',
    'color-danger-hover': '#d42f47',
    'color-danger-subtle': '#2a1519',
    'color-success': '#33d6a6',
    'color-success-subtle': '#152822',
    'color-warning': '#f1c40f',
    'color-warning-subtle': '#2a2515',
    'color-info': '#5bc0de',
    'color-info-subtle': '#152530',
    'color-focus-ring': 'rgba(236, 55, 80, 0.4)',
  },
};

export const DEFAULT_THEME_FILES: Record<string, ThemeDefinition> = {
  light: DEFAULT_LIGHT_THEME,
  dark: DEFAULT_DARK_THEME,
  space: DEFAULT_SPACE_THEME,
  hackclub: DEFAULT_HACKCLUB_THEME,
};
